### ISSUE TITLE
1 - Resume not found ! 

### ISSUE THREAD

**Issue by Ibrah-salama** [ZaTribune/zatribune.github.io#1]
![image](https://github.com/ZaTribune/zatribune.github.io/assets/76173581/f8a29411-c05c-437b-8f33-bfb6e5b07592)

**Comment by ZaTribune** [comment]
Thanks @Ibrah-salama , I forgot to commit a directory.

**Comment by ZaTribune** [comment]
Thanks @Ibrah-salama , I forgot to commit a directory.
